cloud:
  aws:
    region:
      static: sa-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA2IE6R7PEUBIPNY72
      secret-key: 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
    end-point:
      uri: https://sqs.sa-east-1.amazonaws.com/704707165129/MyQueue
     #uri: copiar da fila criada na aws


server:
  port: 8083

app:
  lambda:
    client:
      register: myLambdaTest